### ISSUE TITLE
Bug Report - github action v4 "TypeError: Cannot instantiate typing.Union"

### ISSUE THREAD

**Issue by nitnelave** [codecov/feedback#259]
**Describe the bug**
When updating our codecov action from v3 to v4, I got the following error:

```
Run codecov/codecov-action@v4
  with:
    files: lcov.info
    fail_ci_if_error: true
    codecov_yml_path: .github/codecov.yml
  env:
    CARGO_TERM_COLOR: always
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
==> linux OS detected
https://cli.codecov.io/latest/linux/codecov.SHA256SUM
==> Running version latest
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key 806BB28AED779869: public key "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1

gpg: Signature made Fri Feb  2 14:15:33 2024 UTC
gpg:                using RSA key 27034E7FDB850E0BBC2C62FF806BB28AED779869
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2703 4E7F DB85 0E0B BC2C  62FF 806B B28A ED77 9869

==> Running version v0.4.6
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov --codecov-yml-path .github/codecov.yml create-commit'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov --codecov-yml-path .github/codecov.yml create-commit -C a5fd83b32fa8a79630f66f83cf83fc2b244e6b21 -Z
==> Uploader SHASUM verified (103bfefcc56f76473179e600b96eb8150b0f349ad94836b0f63f03ffac469ad7  codecov)
Traceback (most recent call last):
  File "codecov_cli/main.py", line 81, in <module>
  File "codecov_cli/main.py", line 77, in run
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1077, in main
  File "click/core.py", line 943, in make_context
  File "click/core.py", line 1644, in parse_args
  File "click/core.py", line 1408, in parse_args
  File "click/core.py", line 2400, in handle_parse_result
  File "click/core.py", line 2356, in process_value
  File "click/core.py", line 2344, in type_cast_value
  File "click/core.py", line 2316, in convert
  File "click/types.py", line 83, in __call__
  File "click/types.py", line 928, in convert
  File "click/types.py", line 849, in coerce_path_result
  File "typing.py", line 1275, in __call__
  File "typing.py", line 472, in __call__
TypeError: Cannot instantiate typing.Union
[2389] Failed to execute script 'main' due to unhandled exception!
Error: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

**Environment:**
 - GitHub Actions, ubuntu-latest

**To Reproduce**
See the action in commit https://github.com/lldap/lldap/pull/829/commits/b3150c20ba46ff7e683ccd8a3d548644e1c7dccd

**Expected behavior**
Uploads the coverage.

**Additional context**
codecov.yml:
```yaml
codecov:
  require_ci_to_pass: yes
comment:
  layout: "header,diff,files"
  require_changes: true
  require_base: true
  require_head: true
coverage:
  status:
    project:
      default:
        target: "75%"
        threshold: "0.1%"
        removed_code_behavior: adjust_base
github_checks:
  annotations: true
ignore:
  - "app"
  - "docs"
  - "example_configs"
  - "migration-tool"
  - "scripts"
  - "set-password"
```

**Comment by nitnelave** [comment]
I hadn't seen the activity, but it seems to be fixed now. Thanks!
